// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29vuOD4Vj0wL_UCK3itsQ42t0ajD5q80',
    appId: '1:1033030076476:web:2ae1f4c17c2d20921f5b39',
    messagingSenderId: '1033030076476',
    projectId: 'petcare-71796',
    authDomain: 'petcare-71796.firebaseapp.com',
    storageBucket: 'petcare-71796.firebasestorage.app',
    measurementId: 'G-Z1Z0W2WVKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ztJeRw-GOpA_Xvo7Jd-SGV6Tf7PXi44',
    appId: '1:1033030076476:android:34c9ad994f67345f1f5b39',
    messagingSenderId: '1033030076476',
    projectId: 'petcare-71796',
    storageBucket: 'petcare-71796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABApqAR11GrGEbBhbqJZ6curuoex72SHQ',
    appId: '1:1033030076476:ios:0e3c6d6968ffa2f21f5b39',
    messagingSenderId: '1033030076476',
    projectId: 'petcare-71796',
    storageBucket: 'petcare-71796.firebasestorage.app',
    androidClientId: '1033030076476-05g7ajemu71bt0bgmikjesik73mbc6cb.apps.googleusercontent.com',
    iosClientId: '1033030076476-9ouej1dav2krq08skrfu01ge9fpuiq81.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABApqAR11GrGEbBhbqJZ6curuoex72SHQ',
    appId: '1:1033030076476:ios:0e3c6d6968ffa2f21f5b39',
    messagingSenderId: '1033030076476',
    projectId: 'petcare-71796',
    storageBucket: 'petcare-71796.firebasestorage.app',
    androidClientId: '1033030076476-05g7ajemu71bt0bgmikjesik73mbc6cb.apps.googleusercontent.com',
    iosClientId: '1033030076476-9ouej1dav2krq08skrfu01ge9fpuiq81.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD29vuOD4Vj0wL_UCK3itsQ42t0ajD5q80',
    appId: '1:1033030076476:web:9213e0f469a2387a1f5b39',
    messagingSenderId: '1033030076476',
    projectId: 'petcare-71796',
    authDomain: 'petcare-71796.firebaseapp.com',
    storageBucket: 'petcare-71796.firebasestorage.app',
    measurementId: 'G-N7TGP1XVXC',
  );
}
