// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBr-RxtDpjCmyBDVcTnWy9B3vhludLeEI',
    appId: '1:655901514496:web:e4d14ac52848749ef971e5',
    messagingSenderId: '655901514496',
    projectId: 'petcare-1c571',
    authDomain: 'petcare-1c571.firebaseapp.com',
    storageBucket: 'petcare-1c571.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiq6toaVLxgvPTDZSx7fkIyjE9iNEi9Kc',
    appId: '1:655901514496:android:bc2fb662224f5d3bf971e5',
    messagingSenderId: '655901514496',
    projectId: 'petcare-1c571',
    storageBucket: 'petcare-1c571.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC900xxtnLjIhFvj5aGnGl7KAsWgDDMfX4',
    appId: '1:655901514496:ios:b247cdce0c8e99a5f971e5',
    messagingSenderId: '655901514496',
    projectId: 'petcare-1c571',
    storageBucket: 'petcare-1c571.firebasestorage.app',
    iosClientId: '655901514496-pkbvdtv2cn437i77vvjd6ispgi88nsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC900xxtnLjIhFvj5aGnGl7KAsWgDDMfX4',
    appId: '1:655901514496:ios:b247cdce0c8e99a5f971e5',
    messagingSenderId: '655901514496',
    projectId: 'petcare-1c571',
    storageBucket: 'petcare-1c571.firebasestorage.app',
    iosClientId: '655901514496-pkbvdtv2cn437i77vvjd6ispgi88nsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBr-RxtDpjCmyBDVcTnWy9B3vhludLeEI',
    appId: '1:655901514496:web:05356f5834e01893f971e5',
    messagingSenderId: '655901514496',
    projectId: 'petcare-1c571',
    authDomain: 'petcare-1c571.firebaseapp.com',
    storageBucket: 'petcare-1c571.firebasestorage.app',
  );
}
